# -*- coding: utf-8 -*-
"""Open CV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGqRmcsvChegA6iY8_Y4GLYRDXrzMVyp

# **Open CV (Computer Vision)**

* Open source computer python library
* images, face, video analysis etc
"""

import cv2

img=cv2.imread('/content/drive/MyDrive/Camerin DSML/Augmnetation/Original image/backiee-301825-landscape.jpg')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
resized=cv2.resize(img,(300,300))
edges=cv2.Canny(img,100,200)

from google.colab.patches import cv2_imshow
cv2_imshow(img)

cv2_imshow(gray)

cv2_imshow(resized)

cv2_imshow(edges)

"""# **Example 2**"""

import cv2
from google.colab.patches import cv2_imshow

face_cascade = cv2.CascadeClassifier(
    '/content/drive/MyDrive/Camerin DSML/Open CV/haarcascade_frontalface_default.xml'
)

if face_cascade.empty():
    raise ValueError("Cascade not loaded")

img = cv2.imread('/content/drive/MyDrive/Camerin DSML/Open CV/360_F_498813253_1F67TUXp7RKXETW6ZdavRa3dzwsGNgEd.jpg')

if img is None:
    raise ValueError("Image not loaded")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

cv2_imshow(img)

face_cascade=cv2.CascadeClassifier('/content/drive/MyDrive/Camerin DSML/Open CV/haarcascade_frontalface_default.xml')

img=cv2.imread('/content/drive/MyDrive/Camerin DSML/Open CV/360_F_498813253_1F67TUXp7RKXETW6ZdavRa3dzwsGNgEd.jpg')

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

face=face_cascade.detectMultiScale(gray,1.3,5)

for (x,y,w,h) in faces:
  cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

cv2_imshow(img)
cv2.waitKey(0)

"""# **Example 3**"""

cap=cv2.VideoCapture(0) # is the default camera id

while True:
  ret,frame=cap.read() # capture frame by frame
  if not ret:
    break

  cv2_imshow('Live Webcam',frame)
  if cv2.waitkey(1) & 0xFF==ord('q'):
    break

cap.release()
cv2.destroyAllWindows()

"""# **Example 4**"""

import numpy  as np
import matplotlib.pyplot as plt

img=cv2.imread('/content/drive/MyDrive/Camerin DSML/Open CV/bird.avif')

mask=np.zeros_like(img) # every pixel is set to 0 (black)

height,width=img.shape[:2]
# height, width is the number of rows and columns
center=(width//2,height//2)
radius=min(center[0],center[1])

cv2.circle(mask,center,radius,(255,255,255),-1) # 255 (white), -1 : filling the mask

masked_images=cv2.bitwise_and(img,mask)

fig,ax=plt.subplots(1,2,figsize=(10,5))

ax[0].imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
ax[0].set_title('Original image')

ax[1].imshow(cv2.cvtColor(masked_images,cv2.COLOR_BGR2RGB))
ax[1].set_title('Masked image')

ax[1].axis('off')
ax[0].axis('off')

plt.show()

"""# **Threshhold image**"""

img=cv2.imread('/content/drive/MyDrive/Camerin DSML/Open CV/bird.avif')

gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) # convert image to greyscale

ret,thresh=cv2.threshold(gray_img,127,255,cv2.THRESH_BINARY) # 127-threshold value
# 255-maximum pixel

fig,ax=plt.subplots(1,2,figsize=(10,10))

ax[0].imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
ax[0].set_title('Original Image')

ax[1].imshow(thresh,cmap='gray')
ax[1].set_title('Threshold Image')

ax[0].axis('off')
ax[1].axis('off')

plt.show()

"""# **Rotation**"""

img=cv2.imread('/content/drive/MyDrive/Camerin DSML/Open CV/bird.avif')

angle=80 #80 degree

scale=1 # original size

height,width=img.shape[:2]

rotation_matrix=cv2.getRotationMatrix2D((width/2,height/2),angle,scale)
# width/2,height/2 rotation happens around the center of the image

rotated_img=cv2.warpAffine(img,rotation_matrix,(width,height))
# only the image shift while the frame remains the same

fig,ax=plt.subplots(1,2,figsize=(10,5))

ax[0].imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
ax[0].set_title('Original image')

ax[1].imshow(cv2.cvtColor(rotated_img,cv2.COLOR_BGR2RGB))
ax[1].set_title('Rotated image')

ax[1].axis('off')
ax[0].axis('off')

plt.show()

"""# **Video Capture**"""

import cv2

from IPython.display import Image, display

display(Image(filename="/content/drive/MyDrive/Camerin DSML/Open CV/Zenin Toji.gif"))

cap=cv2.VideoCapture('/content/drive/MyDrive/Camerin DSML/Open CV/Zenin Toji.gif')

if not cap.isOpened():
  print('Error in openning the video')
else:
  ret, frame = cap.read() # Read one frame from the video
  if ret:
    cv2_imshow(frame) # Display the frame
  else:
    print('Could not read frame from video')
cap.release()

cap=cv2.VideoCapture('/content/drive/MyDrive/Camerin DSML/Open CV/Zenin Toji.gif') # is the default camera
if not cap.isOpened():
  print('Error in openning the video')
  exit()

while True:
  ret,frame=cap.read() # capture frame by frame
  if not ret:
    break

  cv2_imshow(frame)
  if cv2.waitKey(1) & 0xFF==ord('q'):
    break
cap.release()
cv2.destroyAllWindows()